import { NextIntlClientProvider } from "next-intl";
import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import SessionWrapper from "@/components/SessionWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <SessionWrapper>
      <html lang={locale} suppressHydrationWarning>
        <NextIntlClientProvider messages={messages}>
          <body>{children}</body>
        </NextIntlClientProvider>
      </html>
    </SessionWrapper>
  );
}
